using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Briosa.Generator;

internal sealed record CommandCatalogGenerationResult(IReadOnlyList<string> Files);

internal static class CommandCatalogGenerator
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower,
        UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow
    };

    public static CommandCatalogGenerationResult Generate(
        string catalogRoot,
        string outputRoot)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(catalogRoot);
        ArgumentException.ThrowIfNullOrWhiteSpace(outputRoot);

        var validation = CommandCatalogValidator.ValidateDirectory(catalogRoot);
        if (!validation.IsValid)
        {
            throw new InvalidDataException(
                $"Catalog generation requires a valid catalog: {string.Join(" ", validation.Errors)}");
        }

        var fullCatalogRoot = Path.GetFullPath(catalogRoot);
        var fullOutputRoot = Path.GetFullPath(outputRoot);
        var generatedFiles = new List<string>();
        foreach (var manifestPath in Directory
            .EnumerateFiles(
                Path.Combine(fullCatalogRoot, "sa"),
                "catalog.json",
                SearchOption.AllDirectories)
            .OrderBy(path => path, StringComparer.Ordinal))
        {
            var manifest = Deserialize<CommandCatalogManifest>(manifestPath);
            var targetDirectory = Path.GetDirectoryName(manifestPath) ??
                throw new InvalidDataException("A catalog manifest has no parent directory.");
            var operations = manifest.OperationFiles
                .Select(path => Deserialize<CommandCatalogOperation>(
                    Path.Combine(
                        targetDirectory,
                        path.Replace('/', Path.DirectorySeparatorChar))))
                .OrderBy(operation => operation.OperationId, StringComparer.Ordinal)
                .ToArray();

            var packagePath = manifest.TargetProtocolPackage.Replace('.', '/');
            WriteGeneratedFile(
                fullOutputRoot,
                $"proto/{packagePath}/operations.proto",
                GenerateProto(manifest, operations),
                generatedFiles);

            var targetNamespace = ToCSharpNamespace(manifest.TargetProtocolPackage);
            var generatedNamespace = $"Briosa.Server.Generated.{targetNamespace["Briosa.".Length..]}";
            WriteGeneratedFile(
                fullOutputRoot,
                $"src/Briosa.Server/Generated/{targetNamespace["Briosa.".Length..].Replace('.', '/')}/Operations.g.cs",
                GenerateWorkerBindings(generatedNamespace, operations),
                generatedFiles);
        }

        return new CommandCatalogGenerationResult(generatedFiles);
    }

    private static string GenerateProto(
        CommandCatalogManifest manifest,
        IReadOnlyList<CommandCatalogOperation> operations)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Generated from the reviewed Briosa command catalog. Do not edit by hand.");
        builder.AppendLine("syntax = \"proto3\";");
        builder.AppendLine();
        builder.Append("package ").Append(manifest.TargetProtocolPackage).AppendLine(";");
        builder.AppendLine();
        builder.AppendLine("import \"briosa/core/v1alpha1/operation_outcomes.proto\";");
        if (operations.SelectMany(operation => operation.Arguments)
            .Any(argument => IsMessageType(argument.SemanticType)))
        {
            builder.Append("import \"")
                .Append(manifest.TargetProtocolPackage.Replace('.', '/'))
                .AppendLine("/values.proto\";");
        }

        builder.AppendLine();
        builder.Append("option csharp_namespace = \"")
            .Append(ToCSharpNamespace(manifest.TargetProtocolPackage))
            .AppendLine("\";");

        foreach (var serviceGroup in operations
            .GroupBy(operation => operation.Protocol.Service, StringComparer.Ordinal)
            .OrderBy(group => group.Key, StringComparer.Ordinal))
        {
            builder.AppendLine();
            builder.Append("service ").Append(serviceGroup.Key).AppendLine(" {");
            foreach (var operation in serviceGroup.OrderBy(
                operation => operation.Protocol.Rpc,
                StringComparer.Ordinal))
            {
                AppendComment(builder, operation.Documentation.Summary, indentation: "  ");
                builder.Append("  rpc ")
                    .Append(operation.Protocol.Rpc)
                    .Append('(')
                    .Append(operation.Protocol.Request)
                    .Append(") returns (")
                    .Append(operation.Protocol.Result)
                    .AppendLine(");");
            }

            builder.AppendLine("}");
        }

        foreach (var operation in operations)
        {
            builder.AppendLine();
            AppendMessage(
                builder,
                operation.Protocol.Request,
                [.. operation.Arguments.Where(IsInput)]);
            builder.AppendLine();
            AppendResultMessage(
                builder,
                operation.Protocol.Result,
                [.. operation.Arguments.Where(IsOutput)]);
        }

        return builder.ToString();
    }

    private static string GenerateWorkerBindings(
        string generatedNamespace,
        IReadOnlyList<CommandCatalogOperation> operations)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Generated from the reviewed Briosa command catalog. Do not edit by hand.");
        builder.AppendLine("using Briosa.Worker.Control;");
        builder.AppendLine();
        builder.Append("namespace ").Append(generatedNamespace).AppendLine(";");

        foreach (var operation in operations)
        {
            var inputs = operation.Arguments.Where(IsInput).ToArray();
            if (inputs.Length != 0)
            {
                throw new NotSupportedException(
                    $"Operation '{operation.OperationId}' has inputs; input adapter generation is owned by issue #16.");
            }

            builder.AppendLine();
            builder.Append("[global::System.CodeDom.Compiler.GeneratedCode(\"Briosa.Generator\", \"1.0\")]")
                .AppendLine();
            builder.Append("internal static class ")
                .Append(operation.Protocol.Service)
                .Append(operation.Protocol.Rpc)
                .AppendLine("Binding");
            builder.AppendLine("{");
            builder.Append("    public const string OperationId = \"")
                .Append(EscapeCSharp(operation.OperationId))
                .AppendLine("\";");
            builder.Append("    public const string StepName = \"")
                .Append(EscapeCSharp(operation.MpStep))
                .AppendLine("\";");

            foreach (var output in operation.Arguments.Where(IsOutput))
            {
                builder.Append("    public const string ")
                    .Append(ToPascalCase(output.ArgumentId))
                    .Append("ArgumentName = \"")
                    .Append(EscapeCSharp(output.MpName))
                    .AppendLine("\";");
                builder.Append("    public const string ")
                    .Append(ToPascalCase(output.ArgumentId))
                    .Append("FieldName = \"")
                    .Append(EscapeCSharp(output.ArgumentId))
                    .AppendLine("\";");
            }

            builder.AppendLine();
            builder.AppendLine("    public static WorkerMpCommand CreateCommand() =>");
            builder.AppendLine("        new(");
            builder.AppendLine("            OperationId,");
            builder.AppendLine("            StepName,");
            builder.AppendLine("            InputArguments: [],");
            var outputs = operation.Arguments.Where(IsOutput).ToArray();
            if (outputs.Length == 0)
            {
                builder.AppendLine("            OutputArguments: []);");
            }
            else
            {
                builder.AppendLine("            OutputArguments:");
                builder.AppendLine("            [");
                foreach (var output in outputs)
                {
                    builder.Append("                new WorkerMpOutputArgument(")
                        .Append(ToPascalCase(output.ArgumentId))
                        .Append("ArgumentName, WorkerMpValueKind.")
                        .Append(ToWorkerValueKind(output.SemanticType))
                        .AppendLine("),");
                }

                builder.AppendLine("            ]);");
            }

            builder.AppendLine("}");
        }

        return builder.ToString();
    }

    private static void AppendMessage(
        StringBuilder builder,
        string name,
        IReadOnlyList<CommandCatalogArgument> arguments)
    {
        if (arguments.Count == 0)
        {
            builder.Append("message ").Append(name).AppendLine(" {}");
            return;
        }

        builder.Append("message ").Append(name).AppendLine(" {");
        foreach (var argument in arguments.OrderBy(argument => argument.Ordinal))
        {
            AppendComment(builder, argument.Documentation, indentation: "  ");
            builder.Append("  ");
            if (!IsMessageType(argument.SemanticType))
            {
                builder.Append("optional ");
            }

            builder.Append(ToProtoType(argument.SemanticType))
                .Append(' ')
                .Append(argument.ArgumentId)
                .Append(" = ")
                .Append((argument.Ordinal + 1).ToString(CultureInfo.InvariantCulture))
                .AppendLine(";");
        }

        builder.AppendLine("}");
    }

    private static void AppendResultMessage(
        StringBuilder builder,
        string name,
        IReadOnlyList<CommandCatalogArgument> arguments)
    {
        builder.Append("message ").Append(name).AppendLine(" {");
        foreach (var argument in arguments.OrderBy(argument => argument.Ordinal))
        {
            AppendComment(builder, argument.Documentation, indentation: "  ");
            builder.Append("  ");
            if (!IsMessageType(argument.SemanticType))
            {
                builder.Append("optional ");
            }

            builder.Append(ToProtoType(argument.SemanticType))
                .Append(' ')
                .Append(argument.ArgumentId)
                .Append(" = ")
                .Append((argument.Ordinal + 1).ToString(CultureInfo.InvariantCulture))
                .AppendLine(";");
        }

        builder.AppendLine("  // Explicit MP and result-only argument retrieval outcome.");
        builder.AppendLine("  briosa.core.v1alpha1.MpExecutionDetails execution = 1000;");
        builder.AppendLine("}");
    }

    private static void AppendComment(StringBuilder builder, string value, string indentation)
    {
        foreach (var line in value.ReplaceLineEndings("\n").Split('\n'))
        {
            builder.Append(indentation).Append("// ").AppendLine(line.Trim());
        }
    }

    private static bool IsInput(CommandCatalogArgument argument) =>
        argument.Direction is "input" or "input_output";

    private static bool IsOutput(CommandCatalogArgument argument) =>
        argument.Direction is "output" or "input_output";

    private static bool IsMessageType(string semanticType) =>
        semanticType is "point_name" or "vector" or "tolerance_vector_options";

    private static string ToProtoType(string semanticType) =>
        semanticType switch
        {
            "logical" => "bool",
            "whole_number" => "int32",
            "floating_point" => "double",
            "string" => "string",
            "point_name" => "PointName",
            "vector" => "Vector3",
            "tolerance_vector_options" => "ToleranceVectorOptions",
            _ => throw new NotSupportedException(
                $"Semantic type '{semanticType}' has no protobuf mapping.")
        };

    private static string ToWorkerValueKind(string semanticType) =>
        semanticType switch
        {
            "logical" => "Logical",
            "whole_number" => "WholeNumber",
            "floating_point" => "FloatingPoint",
            "string" => "Text",
            "point_name" => "PointName",
            "vector" => "Vector",
            "tolerance_vector_options" => "ToleranceVectorOptions",
            _ => throw new NotSupportedException(
                $"Semantic type '{semanticType}' has no worker value mapping.")
        };

    private static string ToCSharpNamespace(string package)
    {
        var segments = package.Split('.');
        return string.Join('.', segments.Select(segment => segment switch
        {
            "briosa" => "Briosa",
            "sa" => "Sa",
            var version when version.StartsWith('v') => ToVersionNamespaceSegment(version),
            _ => ToPascalCase(segment)
        }));
    }

    private static string ToVersionNamespaceSegment(string value)
    {
        var result = char.ToUpperInvariant(value[0]) + value[1..];
        result = result.Replace("alpha", "Alpha", StringComparison.Ordinal);
        return result.Replace("beta", "Beta", StringComparison.Ordinal);
    }

    private static string ToPascalCase(string value) =>
        string.Concat(value
            .Split('_', StringSplitOptions.RemoveEmptyEntries)
            .Select(segment => char.ToUpperInvariant(segment[0]) + segment[1..]));

    private static string EscapeCSharp(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal);

    private static T Deserialize<T>(string path) =>
        JsonSerializer.Deserialize<T>(File.ReadAllText(path), JsonOptions) ??
            throw new InvalidDataException($"Catalog document '{path}' was empty.");

    private static void WriteGeneratedFile(
        string outputRoot,
        string relativePath,
        string content,
        List<string> generatedFiles)
    {
        var normalizedPath = relativePath.Replace('\\', '/');
        var outputPath = Path.Combine(
            outputRoot,
            normalizedPath.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        File.WriteAllText(
            outputPath,
            content.ReplaceLineEndings("\n"),
            new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        generatedFiles.Add(normalizedPath);
    }
}
