using System.Globalization;
using System.Text;
using System.Text.Json;

namespace Briosa.Generator;

internal static class CommandCatalogArtifactGenerator
{
    private static readonly JsonSerializerOptions CoverageJsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower,
        WriteIndented = true
    };

    public static string GenerateWorkerBindings(
        string generatedNamespace,
        string targetNamespace,
        IReadOnlyList<CommandCatalogOperation> operations)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Generated from the reviewed Briosa command catalog. Do not edit by hand.");
        builder.AppendLine("using Briosa.Server.Services;");
        builder.AppendLine("using Briosa.Worker.Control;");
        builder.Append("using TargetProtocol = global::").Append(targetNamespace).AppendLine(";");
        builder.AppendLine();
        builder.Append("namespace ").Append(generatedNamespace).AppendLine(";");

        foreach (var operation in operations)
        {
            AppendBinding(builder, operation);
        }

        return builder.ToString();
    }

    public static string GenerateDocumentation(
        CommandCatalogManifest manifest,
        IReadOnlyList<CommandCatalogOperation> operations)
    {
        var builder = new StringBuilder();
        builder.AppendLine("<!-- <auto-generated /> -->");
        builder.AppendLine("<!-- Generated from the reviewed Briosa command catalog. Do not edit by hand. -->");
        builder.Append("# SpatialAnalyzer ").Append(manifest.SpatialAnalyzerTarget)
            .AppendLine(" operation reference");
        builder.AppendLine();
        builder.Append("Catalog `").Append(manifest.CatalogId).Append("` revision `")
            .Append(manifest.CatalogRevision).AppendLine("`.");
        builder.AppendLine();
        builder.AppendLine("Only explicitly reviewed Briosa operations are listed here. This is not the installed SpatialAnalyzer MP catalog.");

        foreach (var operation in operations)
        {
            builder.AppendLine();
            builder.Append("## `").Append(operation.Protocol.Service).Append('.')
                .Append(operation.Protocol.Rpc).AppendLine("`");
            builder.AppendLine();
            builder.AppendLine(operation.Documentation.Summary);
            builder.AppendLine();
            builder.Append("- Briosa operation: `").Append(operation.OperationId).AppendLine("`");
            builder.Append("- Exact MP step: `").Append(operation.MpStep).AppendLine("`");
            builder.Append("- Stability: `").Append(operation.Stability).AppendLine("`");
            builder.Append("- Effect: `").Append(operation.Risk.Effect).AppendLine("`");
            builder.Append("- Risk flags: ")
                .AppendLine(operation.Risk.Flags.Count == 0
                    ? "none"
                    : string.Join(", ", operation.Risk.Flags.Select(flag => $"`{flag}`")));
            AppendArgumentTable(builder, "Inputs", operation.Arguments.Where(IsInput));
            AppendArgumentTable(builder, "Outputs", operation.Arguments.Where(IsOutput));
        }

        return builder.ToString();
    }

    public static string GenerateCoverageManifest(
        CommandCatalogManifest manifest,
        IReadOnlyList<CommandCatalogOperation> operations)
    {
        var document = new
        {
            schema_version = 1,
            manifest.CatalogId,
            manifest.CatalogRevision,
            manifest.SpatialAnalyzerTarget,
            manifest.TargetProtocolPackage,
            operations = operations.Select(operation => new
            {
                operation.OperationId,
                operation.MpStep,
                service = operation.Protocol.Service,
                rpc = operation.Protocol.Rpc,
                request = operation.Protocol.Request,
                result = operation.Protocol.Result,
                generated = new
                {
                    protocol = true,
                    command_adapter = true,
                    result_adapter = true,
                    documentation = true
                },
                inputs = operation.Arguments.Where(IsInput).OrderBy(argument => argument.Ordinal)
                    .Select(argument => new
                    {
                        argument.ArgumentId,
                        argument.Ordinal,
                        argument.MpName,
                        argument.Direction,
                        argument.SemanticType,
                        setter = argument.SdkBinding.Setter,
                        presence = argument.Input?.Presence,
                        omission_behavior = argument.Input?.OmissionBehavior,
                        default_status = argument.Input?.Default.Status
                    }),
                outputs = operation.Arguments.Where(IsOutput).OrderBy(argument => argument.Ordinal)
                    .Select(argument => new
                    {
                        argument.ArgumentId,
                        argument.Ordinal,
                        argument.MpName,
                        argument.Direction,
                        argument.ResultOnly,
                        argument.SemanticType,
                        getter = argument.SdkBinding.Getter
                    })
            })
        };
        return JsonSerializer.Serialize(document, CoverageJsonOptions) + "\n";
    }

    private static void AppendBinding(StringBuilder builder, CommandCatalogOperation operation)
    {
        var inputs = operation.Arguments.Where(IsInput).OrderBy(argument => argument.Ordinal).ToArray();
        var outputs = operation.Arguments.Where(IsOutput).OrderBy(argument => argument.Ordinal).ToArray();
        ValidateBindings(operation, inputs, outputs);

        builder.AppendLine();
        builder.AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"Briosa.Generator\", \"1.0\")]");
        builder.Append("internal static class ").Append(operation.Protocol.Service)
            .Append(operation.Protocol.Rpc).AppendLine("Binding");
        builder.AppendLine("{");
        builder.Append("    public const string OperationId = \"")
            .Append(EscapeCSharp(operation.OperationId)).AppendLine("\";");
        builder.Append("    public const string StepName = \"")
            .Append(EscapeCSharp(operation.MpStep)).AppendLine("\";");

        foreach (var argument in inputs.Concat(outputs).DistinctBy(argument => argument.ArgumentId))
        {
            var name = ToPascalCase(argument.ArgumentId);
            builder.Append("    public const string ").Append(name).Append("ArgumentName = \"")
                .Append(EscapeCSharp(argument.MpName)).AppendLine("\";");
            builder.Append("    public const string ").Append(name).Append("FieldName = \"")
                .Append(EscapeCSharp(argument.ArgumentId)).AppendLine("\";");
            if (IsInput(argument))
            {
                builder.Append("    public const string ").Append(name).Append("Setter = \"")
                    .Append(EscapeCSharp(argument.SdkBinding.Setter!)).AppendLine("\";");
            }

            if (IsOutput(argument))
            {
                builder.Append("    public const string ").Append(name).Append("Getter = \"")
                    .Append(EscapeCSharp(argument.SdkBinding.Getter!)).AppendLine("\";");
            }
        }

        builder.AppendLine();
        AppendOutputContracts(builder, outputs);
        builder.AppendLine();
        AppendCreateCommand(builder, operation, inputs, outputs);
        builder.AppendLine();
        AppendCreateResult(builder, operation, outputs);
        builder.AppendLine("}");
    }

    private static void ValidateBindings(
        CommandCatalogOperation operation,
        IReadOnlyList<CommandCatalogArgument> inputs,
        CommandCatalogArgument[] outputs)
    {
        foreach (var input in inputs)
        {
            if (input.Input is null || input.SdkBinding.Status != "available" ||
                string.IsNullOrWhiteSpace(input.SdkBinding.Setter))
            {
                throw new NotSupportedException(
                    $"Operation '{operation.OperationId}' input '{input.ArgumentId}' is not generation-ready.");
            }

            if (input.Input.OmissionBehavior == "set_catalog_default" &&
                input.Input.Default.Status != "reviewed")
            {
                throw new NotSupportedException(
                    $"Operation '{operation.OperationId}' input '{input.ArgumentId}' may use only a reviewed catalog default.");
            }
        }

        foreach (var output in outputs)
        {
            if (output.SdkBinding.Status != "available" ||
                string.IsNullOrWhiteSpace(output.SdkBinding.Getter))
            {
                throw new NotSupportedException(
                    $"Operation '{operation.OperationId}' output '{output.ArgumentId}' is not generation-ready.");
            }
        }
    }

    private static void AppendOutputContracts(
        StringBuilder builder,
        CommandCatalogArgument[] outputs)
    {
        builder.AppendLine("    public static IReadOnlyList<OperationOutputContract> OutputContracts { get; } =");
        if (outputs.Length == 0)
        {
            builder.AppendLine("        [];");
            return;
        }

        builder.AppendLine("        [");
        foreach (var output in outputs)
        {
            var name = ToPascalCase(output.ArgumentId);
            builder.Append("            new(").Append(name).Append("FieldName, ")
                .Append(name).Append("ArgumentName, WorkerMpValueKind.")
                .Append(ToWorkerValueKind(output.SemanticType)).AppendLine("),");
        }

        builder.AppendLine("        ];");
    }

    private static void AppendCreateCommand(
        StringBuilder builder,
        CommandCatalogOperation operation,
        IReadOnlyList<CommandCatalogArgument> inputs,
        CommandCatalogArgument[] outputs)
    {
        builder.Append("    public static WorkerMpCommand CreateCommand(TargetProtocol.")
            .Append(operation.Protocol.Request).AppendLine(" request)");
        builder.AppendLine("    {");
        builder.AppendLine("        ArgumentNullException.ThrowIfNull(request);");
        builder.AppendLine("        List<WorkerMpInputArgument> inputs = [];");
        foreach (var input in inputs)
        {
            AppendInputMapping(builder, input);
        }

        builder.AppendLine("        return new WorkerMpCommand(");
        builder.AppendLine("            OperationId,");
        builder.AppendLine("            StepName,");
        builder.AppendLine("            InputArguments: inputs,");
        if (outputs.Length == 0)
        {
            builder.AppendLine("            OutputArguments: []);");
        }
        else
        {
            builder.AppendLine("            OutputArguments:");
            builder.AppendLine("            [");
            foreach (var output in outputs)
            {
                var name = ToPascalCase(output.ArgumentId);
                builder.Append("                new(").Append(name).Append("ArgumentName, WorkerMpValueKind.")
                    .Append(ToWorkerValueKind(output.SemanticType)).Append(", ")
                    .Append(name).AppendLine("Getter),");
            }

            builder.AppendLine("            ]);");
        }

        builder.AppendLine("    }");
    }

    private static void AppendInputMapping(StringBuilder builder, CommandCatalogArgument input)
    {
        var property = ToPascalCase(input.ArgumentId);
        var present = IsMessageType(input.SemanticType)
            ? $"request.{property} is not null"
            : $"request.Has{property}";
        builder.Append("        if (").Append(present).AppendLine(")");
        builder.AppendLine("        {");
        if (IsMessageType(input.SemanticType))
        {
            AppendMessageValidation(builder, input, property, "            ");
        }

        builder.Append("            inputs.Add(").Append(CreateInputExpression(input, $"request.{property}"))
            .AppendLine(");");
        builder.AppendLine("        }");

        if (input.Input!.OmissionBehavior == "set_catalog_default")
        {
            builder.AppendLine("        else");
            builder.AppendLine("        {");
            builder.Append("            inputs.Add(")
                .Append(CreateInputExpression(input, DefaultExpression(input)))
                .AppendLine(");");
            builder.AppendLine("        }");
        }
        else if (input.Input.Presence == "required" ||
                 input.Input.OmissionBehavior == "reject_request")
        {
            builder.AppendLine("        else");
            builder.AppendLine("        {");
            builder.Append("            throw new ArgumentException(\"Required request field '")
                .Append(EscapeCSharp(input.ArgumentId)).AppendLine("' is missing.\", nameof(request));");
            builder.AppendLine("        }");
        }
    }

    private static void AppendMessageValidation(
        StringBuilder builder,
        CommandCatalogArgument input,
        string property,
        string indentation)
    {
        var condition = input.SemanticType switch
        {
            "point_name" => $"!request.{property}.HasCollectionName || !request.{property}.HasGroupName || !request.{property}.HasTargetName",
            "vector" => $"!request.{property}.HasX || !request.{property}.HasY || !request.{property}.HasZ",
            "tolerance_vector_options" => string.Join(" || ", ToleranceNames.Select(name =>
                $"request.{property}.{name} is null || !request.{property}.{name}.HasEnabled || !request.{property}.{name}.HasValue")),
            _ => throw new NotSupportedException()
        };
        builder.Append(indentation).Append("if (").Append(condition).AppendLine(")");
        builder.Append(indentation).AppendLine("{");
        builder.Append(indentation).Append("    throw new ArgumentException(\"Request field '")
            .Append(EscapeCSharp(input.ArgumentId))
            .AppendLine("' must contain every exact-target component.\", nameof(request));");
        builder.Append(indentation).AppendLine("}");
    }

    private static string CreateInputExpression(CommandCatalogArgument input, string valueExpression)
    {
        var name = ToPascalCase(input.ArgumentId);
        var prefix = $"new WorkerMpInputArgument({name}ArgumentName, WorkerMpValueKind.{ToWorkerValueKind(input.SemanticType)}, SdkBinding: {name}Setter, ";
        return input.SemanticType switch
        {
            "logical" => prefix + $"BooleanValue: {valueExpression})",
            "whole_number" => prefix + $"IntegerValue: {valueExpression})",
            "floating_point" => prefix + $"DoubleValue: {valueExpression})",
            "string" => prefix + $"StringValue: {valueExpression})",
            "point_name" => prefix + $"PointNameValue: new({valueExpression}.CollectionName, {valueExpression}.GroupName, {valueExpression}.TargetName))",
            "vector" => prefix + $"VectorValue: new({valueExpression}.X, {valueExpression}.Y, {valueExpression}.Z))",
            "tolerance_vector_options" => prefix +
                $"ToleranceVectorOptionsValue: new({string.Join(", ", ToleranceNames.Select(nameValue => $"new({valueExpression}.{nameValue}.Enabled, {valueExpression}.{nameValue}.Value)"))}))",
            _ => throw new NotSupportedException(
                $"Semantic type '{input.SemanticType}' has no input mapping.")
        };
    }

    private static void AppendCreateResult(
        StringBuilder builder,
        CommandCatalogOperation operation,
        CommandCatalogArgument[] outputs)
    {
        builder.Append("    public static TargetProtocol.").Append(operation.Protocol.Result)
            .AppendLine(" CreateResult(SuccessfulOperationExecution completed)");
        builder.AppendLine("    {");
        builder.AppendLine("        ArgumentNullException.ThrowIfNull(completed);");
        foreach (var output in outputs)
        {
            var name = ToPascalCase(output.ArgumentId);
            builder.Append("        var output").Append(name).Append(" = completed.Execution.OutputValues.Single(value => value.Name == ")
                .Append(name).Append("ArgumentName && value.Kind == WorkerMpValueKind.")
                .Append(ToWorkerValueKind(output.SemanticType)).AppendLine(");");
        }

        builder.Append("        return new TargetProtocol.").Append(operation.Protocol.Result).AppendLine();
        builder.AppendLine("        {");
        foreach (var output in outputs)
        {
            builder.Append("            ").Append(ToPascalCase(output.ArgumentId)).Append(" = ")
                .Append(ResultValueExpression(output, $"output{ToPascalCase(output.ArgumentId)}")).AppendLine(",");
        }

        builder.AppendLine("            Execution = completed.Details");
        builder.AppendLine("        };");
        builder.AppendLine("    }");
    }

    private static string ResultValueExpression(CommandCatalogArgument output, string variable) =>
        output.SemanticType switch
        {
            "logical" => $"{variable}.BooleanValue!.Value",
            "whole_number" => $"{variable}.IntegerValue!.Value",
            "floating_point" => $"{variable}.DoubleValue!.Value",
            "string" => $"{variable}.StringValue!",
            "point_name" => $"new TargetProtocol.PointName {{ CollectionName = {variable}.PointNameValue!.CollectionName, GroupName = {variable}.PointNameValue.GroupName, TargetName = {variable}.PointNameValue.TargetName }}",
            "vector" => $"new TargetProtocol.Vector3 {{ X = {variable}.VectorValue!.X, Y = {variable}.VectorValue.Y, Z = {variable}.VectorValue.Z }}",
            "tolerance_vector_options" => $"new TargetProtocol.ToleranceVectorOptions {{ {string.Join(", ", ToleranceNames.Select(name => $"{name} = new TargetProtocol.ToleranceLimit {{ Enabled = {variable}.ToleranceVectorOptionsValue!.{name}.Enabled, Value = {variable}.ToleranceVectorOptionsValue.{name}.Value }}"))} }}",
            _ => throw new NotSupportedException(
                $"Semantic type '{output.SemanticType}' has no result mapping.")
        };

    private static string DefaultExpression(CommandCatalogArgument input)
    {
        var value = input.Input!.Default.Value ??
            throw new NotSupportedException($"Reviewed default for '{input.ArgumentId}' has no value.");
        return input.SemanticType switch
        {
            "logical" => value.GetBoolean() ? "true" : "false",
            "whole_number" => value.GetInt32().ToString(CultureInfo.InvariantCulture),
            "floating_point" => value.GetDouble().ToString("R", CultureInfo.InvariantCulture) + "d",
            "string" => $"\"{EscapeCSharp(value.GetString() ?? string.Empty)}\"",
            _ => throw new NotSupportedException(
                $"Reviewed defaults for semantic type '{input.SemanticType}' are not supported yet.")
        };
    }

    private static void AppendArgumentTable(
        StringBuilder builder,
        string heading,
        IEnumerable<CommandCatalogArgument> arguments)
    {
        var values = arguments.OrderBy(argument => argument.Ordinal).ToArray();
        builder.AppendLine().Append("### ").AppendLine(heading).AppendLine();
        if (values.Length == 0)
        {
            builder.AppendLine("None.");
            return;
        }

        builder.AppendLine("| Field | MP argument | Direction | Type | SDK binding | Presence / retrieval |");
        builder.AppendLine("| --- | --- | --- | --- | --- | --- |");
        foreach (var argument in values)
        {
            var binding = IsInput(argument) ? argument.SdkBinding.Setter : argument.SdkBinding.Getter;
            var behavior = IsInput(argument)
                ? $"{argument.Input!.Presence}; {argument.Input.OmissionBehavior}; default {argument.Input.Default.Status}"
                : $"result-only {argument.ResultOnly}";
            builder.Append("| `").Append(argument.ArgumentId).Append("` | `")
                .Append(argument.MpName).Append("` | `").Append(argument.Direction)
                .Append("` | `").Append(argument.SemanticType).Append("` | `")
                .Append(binding).Append("` | ").Append(behavior).AppendLine(" |");
        }
    }

    private static bool IsInput(CommandCatalogArgument argument) =>
        argument.Direction is "input" or "input_output";

    private static bool IsOutput(CommandCatalogArgument argument) =>
        argument.Direction is "output" or "input_output";

    private static bool IsMessageType(string semanticType) =>
        semanticType is "point_name" or "vector" or "tolerance_vector_options";

    private static string ToWorkerValueKind(string semanticType) =>
        semanticType switch
        {
            "logical" => "Logical",
            "whole_number" => "WholeNumber",
            "floating_point" => "FloatingPoint",
            "string" => "Text",
            "point_name" => "PointName",
            "vector" => "Vector",
            "tolerance_vector_options" => "ToleranceVectorOptions",
            _ => throw new NotSupportedException(
                $"Semantic type '{semanticType}' has no worker value mapping.")
        };

    private static string ToPascalCase(string value) =>
        string.Concat(value.Split('_', StringSplitOptions.RemoveEmptyEntries)
            .Select(segment => char.ToUpperInvariant(segment[0]) + segment[1..]));

    private static string EscapeCSharp(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal);

    private static readonly string[] ToleranceNames =
    [
        "HighX", "HighY", "HighZ", "HighMagnitude",
        "LowX", "LowY", "LowZ", "LowMagnitude"
    ];
}
