using System.Globalization;
using System.Text;
using System.Text.Json;

namespace Briosa.Generator;

internal static class CommandCatalogArtifactGenerator
{
    private static readonly JsonSerializerOptions CoverageJsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower,
        WriteIndented = true
    };

    public static string GenerateWorkerBindings(
        string generatedNamespace,
        string targetNamespace,
        CommandCatalogManifest manifest,
        IReadOnlyList<CommandCatalogOperation> operations)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Generated from the reviewed Briosa command catalog. Do not edit by hand.");
        builder.AppendLine("using Briosa.Server.Security;");
        builder.AppendLine("using Briosa.Server.Services;");
        builder.AppendLine("using Briosa.Worker.Control;");
        builder.AppendLine("using CoreProtocol = global::Briosa.Core.V1Alpha1;");
        builder.Append("using TargetProtocol = global::").Append(targetNamespace).AppendLine(";");
        builder.AppendLine();
        builder.Append("namespace ").Append(generatedNamespace).AppendLine(";");
        AppendCatalogMetadata(builder, manifest, operations);

        foreach (var operation in operations)
        {
            AppendBinding(builder, operation);
        }

        return builder.ToString();
    }

    public static string GenerateDocumentation(
        CommandCatalogManifest manifest,
        IReadOnlyList<CommandCatalogOperation> operations)
    {
        var builder = new StringBuilder();
        builder.AppendLine("<!-- <auto-generated /> -->");
        builder.AppendLine("<!-- Generated from the reviewed Briosa command catalog. Do not edit by hand. -->");
        builder.Append("# SpatialAnalyzer ").Append(manifest.SpatialAnalyzerTarget)
            .AppendLine(" operation reference");
        builder.AppendLine();
        builder.Append("Catalog `").Append(manifest.CatalogId).Append("` revision `")
            .Append(manifest.CatalogRevision).AppendLine("`.");
        builder.AppendLine();
        builder.AppendLine("Only explicitly reviewed Briosa operations are listed here. This is not the installed SpatialAnalyzer MP catalog.");
        builder.AppendLine();
        builder.AppendLine("## Execution and replay contract");
        builder.AppendLine();
        builder.AppendLine("Every non-OK operation returns typed, value-free execution disposition, worker recovery guidance, replay guidance, and the exact-target replay-safety classification.");
        builder.AppendLine();
        builder.AppendLine("- `not_started`: Briosa proved SDK command execution did not begin. A replay is offered only when the failure is recoverable.");
        builder.AppendLine("- `started_outcome_unknown`: the command may have affected SpatialAnalyzer. `unsafe` and `unknown` operations require reconciliation before replay.");
        builder.AppendLine("- `completed`: Briosa obtained a terminal MP result. Output-retrieval failure does not make replay safe.");
        builder.AppendLine();
        builder.AppendLine("Worker replacement restores availability; it does not change an operation's execution disposition or authorize replay.");

        foreach (var operation in operations)
        {
            var partition = manifest.ProtocolPartitions.Single(partition =>
                string.Equals(
                    partition.Alias,
                    operation.OperationId.Split('.')[0],
                    StringComparison.Ordinal));
            builder.AppendLine();
            builder.Append("## `").Append(operation.Protocol.Service).Append('.')
                .Append(operation.Protocol.Rpc).AppendLine("`");
            builder.AppendLine();
            builder.AppendLine(operation.Documentation.Summary);
            builder.AppendLine();
            builder.Append("- Briosa operation: `").Append(operation.OperationId).AppendLine("`");
            builder.Append("- Inventory key: `").Append(operation.InventoryKey).AppendLine("`");
            builder.Append("- Protocol file: `").Append(partition.ProtoFile).AppendLine("`");
            builder.Append("- Fully qualified method: `/")
                .Append(manifest.TargetProtocolPackage).Append('.')
                .Append(operation.Protocol.Service).Append('/')
                .Append(operation.Protocol.Rpc).AppendLine("`");
            builder.Append("- Exact MP step: `").Append(operation.MpStep).AppendLine("`");
            builder.Append("- Stability: `").Append(operation.Stability).AppendLine("`");
            builder.Append("- Execution scope: `").Append(operation.ExecutionScope)
                .AppendLine("`");
            builder.Append("- Isolation review: ").AppendLine(operation.Documentation.Isolation);
            builder.Append("- Effect: `").Append(operation.Risk.Effect).AppendLine("`");
            builder.Append("- Replay safety: `").Append(operation.Risk.ReplaySafety)
                .AppendLine("`");
            builder.Append("- Risk flags: ")
                .AppendLine(operation.Risk.Flags.Count == 0
                    ? "none"
                    : string.Join(", ", operation.Risk.Flags.Select(flag => $"`{flag}`")));
            AppendArgumentTable(builder, "Inputs", operation.Arguments.Where(IsInput), isInput: true);
            AppendArgumentTable(builder, "Outputs", operation.Arguments.Where(IsOutput), isInput: false);
        }

        return builder.ToString();
    }

    public static string GenerateCoverageManifest(
        CommandCatalogManifest manifest,
        IReadOnlyList<CommandCatalogOperation> operations)
    {
        var partitions = manifest.ProtocolPartitions.ToDictionary(
            partition => partition.Alias,
            StringComparer.Ordinal);
        var document = new
        {
            schema_version = 1,
            generated_by = CommandCatalogGenerator.GeneratedArtifactIdentity,
            manifest.CatalogId,
            manifest.CatalogRevision,
            manifest.SpatialAnalyzerTarget,
            manifest.TargetProtocolPackage,
            operations = operations.Select(operation => new
            {
                operation.OperationId,
                operation.InventoryKey,
                operation.MpStep,
                protocol_file = partitions[operation.OperationId.Split('.')[0]].ProtoFile,
                service = operation.Protocol.Service,
                rpc = operation.Protocol.Rpc,
                request = operation.Protocol.Request,
                result = operation.Protocol.Result,
                fully_qualified_method =
                    $"/{manifest.TargetProtocolPackage}.{operation.Protocol.Service}/{operation.Protocol.Rpc}",
                effect = operation.Risk.Effect,
                execution_scope = operation.ExecutionScope,
                isolation_review = operation.Documentation.Isolation,
                replay_safety = operation.Risk.ReplaySafety,
                generated = new
                {
                    protocol = true,
                    command_adapter = true,
                    result_adapter = true,
                    documentation = true
                },
                inputs = operation.Arguments.Where(IsInput).OrderBy(argument => argument.Ordinal)
                    .Select(argument => new
                    {
                        argument.ArgumentId,
                        argument.Ordinal,
                        argument.SdkOrder,
                        argument.MpName,
                        argument.Direction,
                        argument.SemanticType,
                        argument.DataClassification,
                        field_number = argument.FieldNumbers.Request,
                        setter = argument.SdkBinding.Setter,
                        presence = argument.Input?.Presence,
                        omission_behavior = argument.Input?.OmissionBehavior,
                        default_status = argument.Input?.Default.Status
                    }),
                outputs = operation.Arguments.Where(IsOutput).OrderBy(argument => argument.Ordinal)
                    .Select(argument => new
                    {
                        argument.ArgumentId,
                        argument.Ordinal,
                        argument.SdkOrder,
                        argument.MpName,
                        argument.Direction,
                        argument.ResultOnly,
                        argument.SemanticType,
                        argument.DataClassification,
                        field_number = argument.FieldNumbers.Result,
                        getter = argument.SdkBinding.Getter
                    })
            })
        };
        return JsonSerializer.Serialize(document, CoverageJsonOptions) + "\n";
    }

    private static void AppendCatalogMetadata(
        StringBuilder builder,
        CommandCatalogManifest manifest,
        IReadOnlyList<CommandCatalogOperation> operations)
    {
        builder.AppendLine();
        builder.AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"Briosa.Generator\", \"1.0\")]");
        builder.AppendLine("internal static class TargetCatalogMetadata");
        builder.AppendLine("{");
        AppendConstant(builder, "CatalogId", manifest.CatalogId);
        AppendConstant(builder, "CatalogRevision", manifest.CatalogRevision);
        AppendConstant(builder, "SpatialAnalyzerTarget", manifest.SpatialAnalyzerTarget);
        AppendConstant(builder, "TargetProtocolPackage", manifest.TargetProtocolPackage);
        builder.AppendLine();
        builder.AppendLine("    public static IReadOnlyList<CatalogOperationDescriptor> Operations { get; } =");
        builder.AppendLine("        [");
        foreach (var operation in operations)
        {
            var service = $"{manifest.TargetProtocolPackage}.{operation.Protocol.Service}";
            builder.Append("            new(\"").Append(EscapeCSharp(operation.OperationId))
                .Append("\", \"").Append(EscapeCSharp(operation.MpStep))
                .Append("\", \"").Append(EscapeCSharp(service))
                .Append("\", \"").Append(EscapeCSharp(operation.Protocol.Rpc))
                .Append("\", \"/").Append(EscapeCSharp(service)).Append('/')
                .Append(EscapeCSharp(operation.Protocol.Rpc))
                .Append("\", \"").Append(EscapeCSharp(operation.Risk.Effect))
                .Append("\", CoreProtocol.OperationExecutionScope.")
                .Append(ToPascalCase(operation.ExecutionScope))
                .Append(", CoreProtocol.ReplaySafety.")
                .Append(ToPascalCase(operation.Risk.ReplaySafety))
                .Append(", [")
                .Append(string.Join(", ", operation.Risk.Flags.Select(flag =>
                    $"\"{EscapeCSharp(flag)}\"")))
                .AppendLine("]),");
        }

        builder.AppendLine("        ];");
        builder.AppendLine("}");
    }

    private static void AppendConstant(StringBuilder builder, string name, string value) =>
        builder.Append("    public const string ").Append(name).Append(" = \"")
            .Append(EscapeCSharp(value)).AppendLine("\";");

    private static void AppendBinding(StringBuilder builder, CommandCatalogOperation operation)
    {
        var inputs = operation.Arguments.Where(IsInput).OrderBy(argument => argument.Ordinal).ToArray();
        var outputs = operation.Arguments.Where(IsOutput).OrderBy(argument => argument.Ordinal).ToArray();
        ValidateBindings(operation, inputs, outputs);

        builder.AppendLine();
        builder.AppendLine("[global::System.CodeDom.Compiler.GeneratedCode(\"Briosa.Generator\", \"1.0\")]");
        builder.Append("internal static class ").Append(operation.Protocol.Service)
            .Append(operation.Protocol.Rpc).AppendLine("Binding");
        builder.AppendLine("{");
        builder.Append("    public const string OperationId = \"")
            .Append(EscapeCSharp(operation.OperationId)).AppendLine("\";");
        builder.Append("    public const string StepName = \"")
            .Append(EscapeCSharp(operation.MpStep)).AppendLine("\";");

        foreach (var argument in inputs.Concat(outputs).DistinctBy(argument => argument.ArgumentId))
        {
            var name = ToPascalCase(argument.ArgumentId);
            builder.Append("    public const string ").Append(name).Append("ArgumentName = \"")
                .Append(EscapeCSharp(argument.MpName)).AppendLine("\";");
            builder.Append("    public const string ").Append(name).Append("FieldName = \"")
                .Append(EscapeCSharp(argument.ArgumentId)).AppendLine("\";");
            if (IsInput(argument))
            {
                builder.Append("    public const string ").Append(name).Append("Setter = \"")
                    .Append(EscapeCSharp(argument.SdkBinding.Setter!)).AppendLine("\";");
            }

            if (IsOutput(argument))
            {
                builder.Append("    public const string ").Append(name).Append("Getter = \"")
                    .Append(EscapeCSharp(argument.SdkBinding.Getter!)).AppendLine("\";");
            }
        }

        builder.AppendLine();
        AppendOutputContracts(builder, outputs);
        builder.AppendLine();
        AppendCreateCommand(builder, operation, inputs, outputs);
        builder.AppendLine();
        AppendCreateResult(builder, operation, outputs);
        builder.AppendLine("}");
    }

    private static void ValidateBindings(
        CommandCatalogOperation operation,
        IReadOnlyList<CommandCatalogArgument> inputs,
        CommandCatalogArgument[] outputs)
    {
        foreach (var input in inputs)
        {
            if (input.Input is null || input.SdkBinding.Status != "available" ||
                string.IsNullOrWhiteSpace(input.SdkBinding.Setter))
            {
                throw new NotSupportedException(
                    $"Operation '{operation.OperationId}' input '{input.ArgumentId}' is not generation-ready.");
            }

            if (input.Input.OmissionBehavior == "set_catalog_default" &&
                input.Input.Default.Status != "reviewed")
            {
                throw new NotSupportedException(
                    $"Operation '{operation.OperationId}' input '{input.ArgumentId}' may use only a reviewed catalog default.");
            }
        }

        foreach (var output in outputs)
        {
            if (output.SdkBinding.Status != "available" ||
                string.IsNullOrWhiteSpace(output.SdkBinding.Getter))
            {
                throw new NotSupportedException(
                    $"Operation '{operation.OperationId}' output '{output.ArgumentId}' is not generation-ready.");
            }
        }
    }

    private static void AppendOutputContracts(
        StringBuilder builder,
        CommandCatalogArgument[] outputs)
    {
        builder.AppendLine("    public static IReadOnlyList<OperationOutputContract> OutputContracts { get; } =");
        if (outputs.Length == 0)
        {
            builder.AppendLine("        [];");
            return;
        }

        builder.AppendLine("        [");
        foreach (var output in outputs)
        {
            var name = ToPascalCase(output.ArgumentId);
            builder.Append("            new(").Append(name).Append("FieldName, ")
                .Append(name).Append("ArgumentName, WorkerMpValueKind.")
                .Append(ToWorkerValueKind(output.SemanticType)).AppendLine("),");
        }

        builder.AppendLine("        ];");
    }

    private static void AppendCreateCommand(
        StringBuilder builder,
        CommandCatalogOperation operation,
        IReadOnlyList<CommandCatalogArgument> inputs,
        CommandCatalogArgument[] outputs)
    {
        builder.Append("    public static WorkerMpCommand CreateCommand(TargetProtocol.")
            .Append(operation.Protocol.Request).AppendLine(" request)");
        builder.AppendLine("    {");
        builder.AppendLine("        ArgumentNullException.ThrowIfNull(request);");
        builder.AppendLine("        List<WorkerMpInputArgument> inputs = [];");
        foreach (var input in inputs)
        {
            AppendInputMapping(builder, input);
        }

        builder.AppendLine("        return new WorkerMpCommand(");
        builder.AppendLine("            OperationId,");
        builder.AppendLine("            StepName,");
        builder.AppendLine("            InputArguments: inputs,");
        if (outputs.Length == 0)
        {
            builder.AppendLine("            OutputArguments: []);");
        }
        else
        {
            builder.AppendLine("            OutputArguments:");
            builder.AppendLine("            [");
            foreach (var output in outputs)
            {
                var name = ToPascalCase(output.ArgumentId);
                builder.Append("                new(").Append(name).Append("ArgumentName, WorkerMpValueKind.")
                    .Append(ToWorkerValueKind(output.SemanticType)).Append(", ")
                    .Append(name).AppendLine("Getter),");
            }

            builder.AppendLine("            ]);");
        }

        builder.AppendLine("    }");
    }

    private static void AppendInputMapping(StringBuilder builder, CommandCatalogArgument input)
    {
        var property = ToPascalCase(input.ArgumentId);
        var present = IsMessageType(input.SemanticType)
            ? $"request.{property} is not null"
            : $"request.Has{property}";
        builder.Append("        if (").Append(present).AppendLine(")");
        builder.AppendLine("        {");
        if (RequiresComponentValidation(input.SemanticType))
        {
            AppendMessageValidation(builder, input, property, "            ");
        }

        builder.Append("            inputs.Add(").Append(CreateInputExpression(input, $"request.{property}"))
            .AppendLine(");");
        builder.AppendLine("        }");

        if (input.Input!.OmissionBehavior == "set_catalog_default")
        {
            builder.AppendLine("        else");
            builder.AppendLine("        {");
            builder.Append("            inputs.Add(")
                .Append(CreateInputExpression(input, DefaultExpression(input)))
                .AppendLine(");");
            builder.AppendLine("        }");
        }
        else if (input.Input.Presence == "required" ||
                 input.Input.OmissionBehavior == "reject_request")
        {
            builder.AppendLine("        else");
            builder.AppendLine("        {");
            builder.Append("            throw new ArgumentException(\"Required request field '")
                .Append(EscapeCSharp(input.ArgumentId)).AppendLine("' is missing.\", nameof(request));");
            builder.AppendLine("        }");
        }
    }

    private static void AppendMessageValidation(
        StringBuilder builder,
        CommandCatalogArgument input,
        string property,
        string indentation)
    {
        var value = $"request.{property}";
        var condition = input.SemanticType switch
        {
            "transform" => $"{value}.Values.Count != 16",
            "world_transform" =>
                $"{value}.Transform is null || {value}.Transform.Values.Count != 16 || !{value}.HasScaleFactor",
            "rgb_color" =>
                $"!{value}.HasRed || {value}.Red > byte.MaxValue || !{value}.HasGreen || {value}.Green > byte.MaxValue || !{value}.HasBlue || {value}.Blue > byte.MaxValue",
            "file_reference" => $"!{value}.HasPath || !{value}.HasEmbeddedFile",
            "font" =>
                $"!{value}.HasFontName || !{value}.HasSize || {value}.Size > byte.MaxValue || {value}.Color is null || !{value}.Color.HasRed || {value}.Color.Red > byte.MaxValue || !{value}.Color.HasGreen || {value}.Color.Green > byte.MaxValue || !{value}.Color.HasBlue || {value}.Color.Blue > byte.MaxValue",
            "angular_unit" or "distance_unit" or "temperature_unit" =>
                $"{value} == 0 || !Enum.IsDefined({value})",
            "point_name" => MissingPointNameComponents(value),
            "vector" => $"!{value}.HasX || !{value}.HasY || !{value}.HasZ",
            "tolerance_vector_options" => string.Join(" || ", ToleranceNames.Select(name =>
                $"{value}.{name} is null || !{value}.{name}.HasEnabled || !{value}.{name}.HasValue")),
            "collection_instrument_id" =>
                $"!{value}.HasCollectionName || !{value}.HasInstrumentId",
            "collection_machine_id" =>
                $"!{value}.HasCollectionName || !{value}.HasMachineId",
            "collection_item_name" => MissingCollectionItemNameComponents(value),
            "collection_object_name" => MissingCollectionObjectNameComponents(value),
            "collection_vector_group_name" =>
                $"!{value}.HasCollectionName || !{value}.HasVectorGroupName",
            "collection_instrument_id_list" =>
                $"{value}.Values.Any(item => !item.HasCollectionName || !item.HasInstrumentId)",
            "collection_group_name_list" =>
                $"{value}.Values.Any(item => !item.HasCollectionName || !item.HasGroupName)",
            "collection_item_name_list" =>
                $"{value}.Values.Any(item => {MissingCollectionItemNameComponents("item")})",
            "collection_object_name_list" =>
                $"{value}.Values.Any(item => {MissingCollectionObjectNameComponents("item")})",
            "collection_vector_group_name_list" =>
                $"{value}.Values.Any(item => !item.HasCollectionName || !item.HasVectorGroupName)",
            "point_name_list" =>
                $"{value}.Values.Any(item => {MissingPointNameComponents("item")})",
            "vector_name_list" =>
                $"{value}.Values.Any(item => !item.HasCollectionName || !item.HasGroupName || !item.HasName)",
            _ => SpecializedValueMappings.ValidationCondition(input.SemanticType, value)
        };
        builder.Append(indentation).Append("if (").Append(condition).AppendLine(")");
        builder.Append(indentation).AppendLine("{");
        builder.Append(indentation).Append("    throw new ArgumentException(\"Request field '")
            .Append(EscapeCSharp(input.ArgumentId))
            .AppendLine("' must contain every exact-target component.\", nameof(request));");
        builder.Append(indentation).AppendLine("}");
    }

    private static string MissingPointNameComponents(string value) =>
        $"!{value}.HasCollectionName || !{value}.HasGroupName || !{value}.HasTargetName";

    private static string MissingCollectionItemNameComponents(string value) =>
        $"!{value}.HasCollectionName || !{value}.HasItemName || !{value}.HasItemType || {value}.ItemType == TargetProtocol.ItemType.Unspecified || !Enum.IsDefined({value}.ItemType)";

    private static string MissingCollectionObjectNameComponents(string value) =>
        $"!{value}.HasCollectionName || !{value}.HasObjectName || !{value}.HasObjectType || {value}.ObjectType == TargetProtocol.ObjectType.Unspecified || !Enum.IsDefined({value}.ObjectType)";
    private static string CreateInputExpression(CommandCatalogArgument input, string valueExpression)
    {
        var name = ToPascalCase(input.ArgumentId);
        var prefix = $"new WorkerMpInputArgument({name}ArgumentName, WorkerMpValueKind.{ToWorkerValueKind(input.SemanticType)}, SdkBinding: {name}Setter, ";
        return input.SemanticType switch
        {
            "logical" => prefix + $"BooleanValue: {valueExpression})",
            "whole_number" => prefix + $"IntegerValue: {valueExpression})",
            "floating_point" => prefix + $"DoubleValue: {valueExpression})",
            "string" or
            "chart_name" or
            "cloud_name" or
            "collection_name" or
            "frame_name" or
            "vector_group_name" or
            "view_name" => prefix + $"StringValue: {valueExpression})",
            "double_array" => prefix +
                $"DoubleArrayValue: new([.. {valueExpression}.Values]))",
            "edit_text" => prefix +
                $"StringListValue: new([.. {valueExpression}.Values]))",
            "transform" => prefix +
                $"TransformValue: new([.. {valueExpression}.Values]))",
            "world_transform" => prefix +
                $"WorldTransformValue: new(new WorkerTransformValue([.. {valueExpression}.Transform.Values]), {valueExpression}.ScaleFactor))",
            "rgb_color" => prefix +
                $"RgbColorValue: new((byte){valueExpression}.Red, (byte){valueExpression}.Green, (byte){valueExpression}.Blue))",
            "file_reference" => prefix +
                $"FileReferenceValue: new({valueExpression}.Path, {valueExpression}.EmbeddedFile))",
            "angular_unit" => prefix +
                $"AngularUnitValue: (WorkerAngularUnitValue)(int){valueExpression})",
            "distance_unit" => prefix +
                $"DistanceUnitValue: (WorkerDistanceUnitValue)(int){valueExpression})",
            "temperature_unit" => prefix +
                $"TemperatureUnitValue: (WorkerTemperatureUnitValue)(int){valueExpression})",
            "font" => prefix +
                $"FontValue: new({valueExpression}.FontName, (byte){valueExpression}.Size, new WorkerRgbColorValue((byte){valueExpression}.Color.Red, (byte){valueExpression}.Color.Green, (byte){valueExpression}.Color.Blue)))",
            "point_name" => prefix + $"PointNameValue: new({valueExpression}.CollectionName, {valueExpression}.GroupName, {valueExpression}.TargetName))",
            "vector" => prefix + $"VectorValue: new({valueExpression}.X, {valueExpression}.Y, {valueExpression}.Z))",
            "tolerance_vector_options" => prefix +
                $"ToleranceVectorOptionsValue: new({string.Join(", ", ToleranceNames.Select(nameValue => $"new({valueExpression}.{nameValue}.Enabled, {valueExpression}.{nameValue}.Value)"))}))",
            "collection_instrument_id" => prefix +
                $"CollectionInstrumentIdValue: new({valueExpression}.CollectionName, {valueExpression}.InstrumentId))",
            "collection_instrument_id_list" => prefix +
                $"CollectionInstrumentIdListValue: new([.. {valueExpression}.Values.Select(value => new WorkerCollectionInstrumentIdValue(value.CollectionName, value.InstrumentId))]))",
            "collection_machine_id" => prefix +
                $"CollectionMachineIdValue: new({valueExpression}.CollectionName, {valueExpression}.MachineId))",
            "collection_item_name" => prefix +
                $"CollectionItemNameValue: new({valueExpression}.CollectionName, {valueExpression}.ItemName, (WorkerItemTypeValue)(int){valueExpression}.ItemType))",
            "collection_item_name_list" => prefix +
                $"CollectionItemNameListValue: new([.. {valueExpression}.Values.Select(value => new WorkerCollectionItemNameValue(value.CollectionName, value.ItemName, (WorkerItemTypeValue)(int)value.ItemType))]))",
            "collection_object_name" => prefix +
                $"CollectionObjectNameValue: new({valueExpression}.CollectionName, {valueExpression}.ObjectName, (WorkerObjectTypeValue)(int){valueExpression}.ObjectType))",
            "collection_object_name_list" => prefix +
                $"CollectionObjectNameListValue: new([.. {valueExpression}.Values.Select(value => new WorkerCollectionObjectNameValue(value.CollectionName, value.ObjectName, (WorkerObjectTypeValue)(int)value.ObjectType))]))",
            "collection_group_name_list" => prefix +
                $"CollectionGroupNameListValue: new([.. {valueExpression}.Values.Select(value => new WorkerCollectionGroupNameValue(value.CollectionName, value.GroupName))]))",
            "collection_vector_group_name" => prefix +
                $"CollectionVectorGroupNameValue: new({valueExpression}.CollectionName, {valueExpression}.VectorGroupName))",
            "collection_vector_group_name_list" => prefix +
                $"CollectionVectorGroupNameListValue: new([.. {valueExpression}.Values.Select(value => new WorkerCollectionVectorGroupNameValue(value.CollectionName, value.VectorGroupName))]))",
            "point_name_list" => prefix +
                $"PointNameListValue: new([.. {valueExpression}.Values.Select(value => new WorkerPointNameValue(value.CollectionName, value.GroupName, value.TargetName))]))",
            "string_list" => prefix +
                $"StringListValue: new([.. {valueExpression}.Values]))",
            "vector_name_list" => prefix +
                $"VectorNameListValue: new([.. {valueExpression}.Values.Select(value => new WorkerVectorNameValue(value.CollectionName, value.GroupName, value.Name))]))",
            _ => SpecializedValueMappings.CreateInputExpression(input.SemanticType, prefix, valueExpression)
        };
    }
    private static void AppendCreateResult(
        StringBuilder builder,
        CommandCatalogOperation operation,
        CommandCatalogArgument[] outputs)
    {
        builder.Append("    public static TargetProtocol.").Append(operation.Protocol.Result)
            .AppendLine(" CreateResult(SuccessfulOperationExecution completed)");
        builder.AppendLine("    {");
        builder.AppendLine("        ArgumentNullException.ThrowIfNull(completed);");
        foreach (var output in outputs)
        {
            var name = ToPascalCase(output.ArgumentId);
            builder.Append("        var output").Append(name).Append(" = completed.Execution.OutputValues.Single(value => value.Name == ")
                .Append(name).Append("ArgumentName && value.Kind == WorkerMpValueKind.")
                .Append(ToWorkerValueKind(output.SemanticType)).AppendLine(");");
        }

        builder.Append("        return new TargetProtocol.").Append(operation.Protocol.Result).AppendLine();
        builder.AppendLine("        {");
        foreach (var output in outputs)
        {
            builder.Append("            ").Append(ToPascalCase(output.ArgumentId)).Append(" = ")
                .Append(ResultValueExpression(output, $"output{ToPascalCase(output.ArgumentId)}")).AppendLine(",");
        }

        builder.AppendLine("            Execution = completed.Details");
        builder.AppendLine("        };");
        builder.AppendLine("    }");
    }

    private static string ResultValueExpression(CommandCatalogArgument output, string variable) =>
        output.SemanticType switch
        {
            "logical" => $"{variable}.BooleanValue!.Value",
            "whole_number" => $"{variable}.IntegerValue!.Value",
            "floating_point" => $"{variable}.DoubleValue!.Value",
            "string" or
            "chart_name" or
            "cloud_name" or
            "collection_name" or
            "frame_name" or
            "vector_group_name" or
            "view_name" => $"{variable}.StringValue!",
            "double_array" =>
                $"new TargetProtocol.DoubleArray {{ Values = {{ {variable}.DoubleArrayValue!.Values }} }}",
            "edit_text" =>
                $"new TargetProtocol.StringList {{ Values = {{ {variable}.StringListValue!.Values }} }}",
            "transform" =>
                $"new TargetProtocol.Transform {{ Values = {{ {variable}.TransformValue!.Values }} }}",
            "world_transform" =>
                $"new TargetProtocol.WorldTransform {{ Transform = new TargetProtocol.Transform {{ Values = {{ {variable}.WorldTransformValue!.Transform.Values }} }}, ScaleFactor = {variable}.WorldTransformValue.ScaleFactor }}",
            "file_reference" =>
                $"new TargetProtocol.FileReference {{ Path = {variable}.FileReferenceValue!.Path, EmbeddedFile = {variable}.FileReferenceValue.EmbeddedFile }}",
            "point_name" => $"new TargetProtocol.PointName {{ CollectionName = {variable}.PointNameValue!.CollectionName, GroupName = {variable}.PointNameValue.GroupName, TargetName = {variable}.PointNameValue.TargetName }}",
            "vector" => $"new TargetProtocol.Vector3 {{ X = {variable}.VectorValue!.X, Y = {variable}.VectorValue.Y, Z = {variable}.VectorValue.Z }}",
            "tolerance_vector_options" => $"new TargetProtocol.ToleranceVectorOptions {{ {string.Join(", ", ToleranceNames.Select(name => $"{name} = new TargetProtocol.ToleranceLimit {{ Enabled = {variable}.ToleranceVectorOptionsValue!.{name}.Enabled, Value = {variable}.ToleranceVectorOptionsValue.{name}.Value }}"))} }}",
            "collection_instrument_id" =>
                $"new TargetProtocol.CollectionInstrumentId {{ CollectionName = {variable}.CollectionInstrumentIdValue!.CollectionName, InstrumentId = {variable}.CollectionInstrumentIdValue.InstrumentId }}",
            "collection_instrument_id_list" =>
                $"new TargetProtocol.CollectionInstrumentIdList {{ Values = {{ {variable}.CollectionInstrumentIdListValue!.Values.Select(value => new TargetProtocol.CollectionInstrumentId {{ CollectionName = value.CollectionName, InstrumentId = value.InstrumentId }}) }} }}",
            "collection_machine_id" =>
                $"new TargetProtocol.CollectionMachineId {{ CollectionName = {variable}.CollectionMachineIdValue!.CollectionName, MachineId = {variable}.CollectionMachineIdValue.MachineId }}",
            "collection_item_name" =>
                $"new TargetProtocol.CollectionItemName {{ CollectionName = {variable}.CollectionItemNameValue!.CollectionName, ItemName = {variable}.CollectionItemNameValue.ItemName, ItemType = (TargetProtocol.ItemType)(int){variable}.CollectionItemNameValue.ItemType }}",
            "collection_item_name_list" =>
                $"new TargetProtocol.CollectionItemNameList {{ Values = {{ {variable}.CollectionItemNameListValue!.Values.Select(value => new TargetProtocol.CollectionItemName {{ CollectionName = value.CollectionName, ItemName = value.ItemName, ItemType = (TargetProtocol.ItemType)(int)value.ItemType }}) }} }}",
            "collection_object_name" =>
                $"new TargetProtocol.CollectionObjectName {{ CollectionName = {variable}.CollectionObjectNameValue!.CollectionName, ObjectName = {variable}.CollectionObjectNameValue.ObjectName, ObjectType = (TargetProtocol.ObjectType)(int){variable}.CollectionObjectNameValue.ObjectType }}",
            "collection_object_name_list" =>
                $"new TargetProtocol.CollectionObjectNameList {{ Values = {{ {variable}.CollectionObjectNameListValue!.Values.Select(value => new TargetProtocol.CollectionObjectName {{ CollectionName = value.CollectionName, ObjectName = value.ObjectName, ObjectType = (TargetProtocol.ObjectType)(int)value.ObjectType }}) }} }}",
            "collection_group_name_list" =>
                $"new TargetProtocol.CollectionGroupNameList {{ Values = {{ {variable}.CollectionGroupNameListValue!.Values.Select(value => new TargetProtocol.CollectionGroupName {{ CollectionName = value.CollectionName, GroupName = value.GroupName }}) }} }}",
            "collection_vector_group_name" =>
                $"new TargetProtocol.CollectionVectorGroupName {{ CollectionName = {variable}.CollectionVectorGroupNameValue!.CollectionName, VectorGroupName = {variable}.CollectionVectorGroupNameValue.VectorGroupName }}",
            "collection_vector_group_name_list" =>
                $"new TargetProtocol.CollectionVectorGroupNameList {{ Values = {{ {variable}.CollectionVectorGroupNameListValue!.Values.Select(value => new TargetProtocol.CollectionVectorGroupName {{ CollectionName = value.CollectionName, VectorGroupName = value.VectorGroupName }}) }} }}",
            "point_name_list" =>
                $"new TargetProtocol.PointNameList {{ Values = {{ {variable}.PointNameListValue!.Values.Select(value => new TargetProtocol.PointName {{ CollectionName = value.CollectionName, GroupName = value.GroupName, TargetName = value.TargetName }}) }} }}",
            "string_list" =>
                $"new TargetProtocol.StringList {{ Values = {{ {variable}.StringListValue!.Values }} }}",
            "vector_name_list" =>
                $"new TargetProtocol.VectorNameList {{ Values = {{ {variable}.VectorNameListValue!.Values.Select(value => new TargetProtocol.VectorName {{ CollectionName = value.CollectionName, GroupName = value.GroupName, Name = value.VectorName }}) }} }}",
            _ => SpecializedValueMappings.ResultValueExpression(output.SemanticType, variable)
        };

    private static string DefaultExpression(CommandCatalogArgument input)
    {
        var value = input.Input!.Default.Value ??
            throw new NotSupportedException($"Reviewed default for '{input.ArgumentId}' has no value.");
        return input.SemanticType switch
        {
            "logical" => value.GetBoolean() ? "true" : "false",
            "whole_number" => value.GetInt32().ToString(CultureInfo.InvariantCulture),
            "floating_point" => value.GetDouble().ToString("R", CultureInfo.InvariantCulture) + "d",
            "string" or
            "chart_name" or
            "cloud_name" or
            "collection_name" or
            "frame_name" or
            "vector_group_name" or
            "view_name" => $"\"{EscapeCSharp(value.GetString() ?? string.Empty)}\"",
            _ => SpecializedValueMappings.DefaultExpression(input.SemanticType, value)
        };
    }

    private static void AppendArgumentTable(
        StringBuilder builder,
        string heading,
        IEnumerable<CommandCatalogArgument> arguments,
        bool isInput)
    {
        var values = arguments.OrderBy(argument => argument.Ordinal).ToArray();
        builder.AppendLine().Append("### ").AppendLine(heading).AppendLine();
        if (values.Length == 0)
        {
            builder.AppendLine("None.");
            return;
        }

        builder.AppendLine("| Field | Number | MP ordinal | SDK order | MP argument | Direction | Type | Data classification | SDK binding | Presence / retrieval |");
        builder.AppendLine("| --- | ---: | ---: | ---: | --- | --- | --- | --- | --- | --- |");
        foreach (var argument in values)
        {
            var binding = isInput ? argument.SdkBinding.Setter : argument.SdkBinding.Getter;
            var fieldNumber = isInput
                ? argument.FieldNumbers.Request
                : argument.FieldNumbers.Result;
            var behavior = isInput
                ? $"{argument.Input!.Presence}; {argument.Input.OmissionBehavior}; default {argument.Input.Default.Status}"
                : $"result-only {argument.ResultOnly}";
            builder.Append("| `").Append(argument.ArgumentId).Append("` | ")
                .Append(fieldNumber).Append(" | ")
                .Append(argument.Ordinal).Append(" | ")
                .Append(argument.SdkOrder).Append(" | `")
                .Append(argument.MpName).Append("` | `").Append(argument.Direction)
                .Append("` | `").Append(argument.SemanticType).Append("` | `")
                .Append(argument.DataClassification).Append("` | `")
                .Append(binding).Append("` | ").Append(behavior).AppendLine(" |");
        }
    }

    private static bool IsInput(CommandCatalogArgument argument) =>
        argument.Direction is "input" or "input_output";

    private static bool IsOutput(CommandCatalogArgument argument) =>
        argument.Direction is "output" or "input_output";

    private static bool IsMessageType(string semanticType) =>
        semanticType is
            "double_array" or
            "edit_text" or
            "transform" or
            "world_transform" or
            "rgb_color" or
            "file_reference" or
            "font" or
            "point_name" or
            "vector" or
            "tolerance_vector_options" or
            "collection_group_name_list" or
            "collection_instrument_id" or
            "collection_instrument_id_list" or
            "collection_machine_id" or
            "collection_item_name" or
            "collection_item_name_list" or
            "collection_object_name" or
            "collection_object_name_list" or
            "collection_vector_group_name" or
            "collection_vector_group_name_list" or
            "point_name_list" or
            "string_list" or
            "vector_name_list" ||
        SpecializedValueMappings.IsStructured(semanticType);

    private static bool RequiresComponentValidation(string semanticType) =>
        semanticType is
            "transform" or
            "world_transform" or
            "rgb_color" or
            "file_reference" or
            "font" or
            "angular_unit" or
            "distance_unit" or
            "temperature_unit" ||
            SpecializedValueMappings.IsSupported(semanticType) ||
        (IsMessageType(semanticType) &&
         semanticType is not "string_list" and not "double_array" and not "edit_text");

    private static string ToWorkerValueKind(string semanticType) =>
        semanticType switch
        {
            "logical" => "Logical",
            "whole_number" => "WholeNumber",
            "floating_point" => "FloatingPoint",
            "string" => "Text",
            "double_array" => "DoubleArray",
            "edit_text" => "EditText",
            "transform" => "Transform",
            "world_transform" => "WorldTransform",
            "rgb_color" => "RgbColor",
            "file_reference" => "FileReference",
            "angular_unit" => "AngularUnit",
            "distance_unit" => "DistanceUnit",
            "temperature_unit" => "TemperatureUnit",
            "font" => "Font",
            "point_name" => "PointName",
            "vector" => "Vector",
            "tolerance_vector_options" => "ToleranceVectorOptions",
            "chart_name" => "ChartName",
            "cloud_name" => "CloudName",
            "collection_group_name_list" => "CollectionGroupNameList",
            "collection_instrument_id" => "CollectionInstrumentId",
            "collection_instrument_id_list" => "CollectionInstrumentIdList",
            "collection_machine_id" => "CollectionMachineId",
            "collection_name" => "CollectionName",
            "collection_item_name" => "CollectionItemName",
            "collection_item_name_list" => "CollectionItemNameList",
            "collection_object_name" => "CollectionObjectName",
            "collection_object_name_list" => "CollectionObjectNameList",
            "collection_vector_group_name" => "CollectionVectorGroupName",
            "collection_vector_group_name_list" => "CollectionVectorGroupNameList",
            "frame_name" => "FrameName",
            "point_name_list" => "PointNameList",
            "string_list" => "StringList",
            "vector_group_name" => "VectorGroupName",
            "vector_name_list" => "VectorNameList",
            "view_name" => "ViewName",
            _ => SpecializedValueMappings.ToTypeName(semanticType)
        };
    private static string ToPascalCase(string value) =>
        string.Concat(value.Split('_', StringSplitOptions.RemoveEmptyEntries)
            .Select(segment => char.ToUpperInvariant(segment[0]) + segment[1..]));

    private static string EscapeCSharp(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal);

    private static readonly string[] ToleranceNames =
    [
        "HighX", "HighY", "HighZ", "HighMagnitude",
        "LowX", "LowY", "LowZ", "LowMagnitude"
    ];
}
