namespace Briosa.Worker.Sdk;

internal enum SdkRelationshipWeightingModeValue { NormalizeEquationCount, NormalizeEquationCountAndToleranceWidth, ResetAllWeights, NormalizeSquareRootEquationCount, NormalizeSquareRootAndToleranceWidth }
