using Briosa.Worker.Control;
namespace Briosa.Worker.Sdk;

internal sealed record SdkInputArgument(
    string Name,
    WorkerMpValueKind Kind,
    bool? BooleanValue = null,
    int? IntegerValue = null,
    double? DoubleValue = null,
    string? StringValue = null,
    WorkerPointNameValue? PointNameValue = null,
    WorkerVectorValue? VectorValue = null,
    WorkerToleranceVectorOptionsValue? ToleranceVectorOptionsValue = null,
    WorkerCollectionInstrumentIdValue? CollectionInstrumentIdValue = null,
    WorkerCollectionInstrumentIdListValue? CollectionInstrumentIdListValue = null,
    WorkerCollectionMachineIdValue? CollectionMachineIdValue = null,
    WorkerCollectionItemNameValue? CollectionItemNameValue = null,
    WorkerCollectionItemNameListValue? CollectionItemNameListValue = null,
    WorkerCollectionObjectNameValue? CollectionObjectNameValue = null,
    WorkerCollectionObjectNameListValue? CollectionObjectNameListValue = null,
    WorkerCollectionGroupNameListValue? CollectionGroupNameListValue = null,
    WorkerCollectionVectorGroupNameValue? CollectionVectorGroupNameValue = null,
    WorkerCollectionVectorGroupNameListValue? CollectionVectorGroupNameListValue = null,
    WorkerPointNameListValue? PointNameListValue = null,
    WorkerStringListValue? StringListValue = null,
    WorkerVectorNameListValue? VectorNameListValue = null,
    WorkerDoubleArrayValue? DoubleArrayValue = null,
    WorkerTransformValue? TransformValue = null,
    WorkerWorldTransformValue? WorldTransformValue = null,
    WorkerRgbColorValue? RgbColorValue = null,
    WorkerFileReferenceValue? FileReferenceValue = null,
    WorkerAngularUnitValue? AngularUnitValue = null,
    WorkerDistanceUnitValue? DistanceUnitValue = null,
    WorkerTemperatureUnitValue? TemperatureUnitValue = null,
    WorkerFontValue? FontValue = null,
    ISdkSpecializedEnumValue? SpecializedEnumValue = null,
    SdkAutoFilterProximitySettingsValue? AutoFilterProximitySettingsValue = null,
    SdkBSplineFitOptionsValue? BSplineFitOptionsValue = null,
    SdkCloudThinningOptionsValue? CloudThinningOptionsValue = null,
    SdkColorizationOptionsValue? ColorizationOptionsValue = null,
    WorkerFitConstraintScalarOptionsValue? FitConstraintScalarOptionsValue = null,
    SdkFitDegreeOfFreedomOptionsValue? FitDegreeOfFreedomOptionsValue = null,
    SdkReportOutputOptionsValue? ReportOutputOptionsValue = null,
    SdkReportViewOptionsValue? ReportViewOptionsValue = null,
    WorkerToleranceScalarOptionsValue? ToleranceScalarOptionsValue = null,
    SdkProjectionOptionsValue? ProjectionOptionsValue = null,
    SdkPointDeltaReportOptionsValue? PointDeltaReportOptionsValue = null,
    SdkUdpTransmitSettingsValue? UdpTransmitSettingsValue = null,
    string? SdkBinding = null);
