using System.Text.Json.Serialization;

namespace Briosa.Worker.Control;

public sealed record WorkerMpOutputValue(
    string Name,
    WorkerMpValueKind Kind,
    bool Retrieved,
    bool? BooleanValue = null,
    int? IntegerValue = null,
    double? DoubleValue = null,
    string? StringValue = null,
    WorkerPointNameValue? PointNameValue = null,
    WorkerVectorValue? VectorValue = null,
    WorkerToleranceVectorOptionsValue? ToleranceVectorOptionsValue = null,
    WorkerCollectionInstrumentIdValue? CollectionInstrumentIdValue = null,
    WorkerCollectionInstrumentIdListValue? CollectionInstrumentIdListValue = null,
    WorkerCollectionMachineIdValue? CollectionMachineIdValue = null,
    WorkerCollectionItemNameValue? CollectionItemNameValue = null,
    WorkerCollectionItemNameListValue? CollectionItemNameListValue = null,
    WorkerCollectionObjectNameValue? CollectionObjectNameValue = null,
    WorkerCollectionObjectNameListValue? CollectionObjectNameListValue = null,
    WorkerCollectionGroupNameListValue? CollectionGroupNameListValue = null,
    WorkerCollectionVectorGroupNameValue? CollectionVectorGroupNameValue = null,
    WorkerCollectionVectorGroupNameListValue? CollectionVectorGroupNameListValue = null,
    WorkerPointNameListValue? PointNameListValue = null,
    WorkerStringListValue? StringListValue = null,
    WorkerVectorNameListValue? VectorNameListValue = null,
    WorkerDoubleArrayValue? DoubleArrayValue = null,
    WorkerTransformValue? TransformValue = null,
    WorkerWorldTransformValue? WorldTransformValue = null,
    WorkerFileReferenceValue? FileReferenceValue = null,
    WorkerFitConstraintScalarOptionsValue? FitConstraintScalarOptionsValue = null,
    WorkerToleranceScalarOptionsValue? ToleranceScalarOptionsValue = null,
    [property: JsonIgnore] string? DiagnosticCode = null);
