namespace Briosa.Worker.Control;

[System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1027:Mark enums with FlagsAttribute", Justification = "Discrete protocol values retain the reserved 2026-only numeric slot.")]
public enum WorkerItemTypeValue
{
    Unspecified,
    Any,
    Alignment,
    Annotation,
    BSpline,
    CalibrationApplianceNode,
    CalloutView,
    Chart,
    Circle,
    Cloud,
    ScanStripeCloud = 11,
    CrossSectionCloud,
    Cone,
    Cylinder,
    Datum,
    Dimension,
    Ellipse,
    Event,
    FeatureCheck,
    Frame,
    FrameSet,
    Line,
    Paraboloid,
    Perimeter,
    Picture,
    Plane,
    PointGroup,
    PointSet,
    PolySurface,
    Relationship,
    SaDoc,
    SaReport,
    SaReportTemplate,
    ScaleBar,
    ScanStripeMesh,
    Slot,
    Sphere,
    Surface,
    Table,
    TcpFixture,
    Torus,
    VectorGroup
}
