namespace Briosa.Worker.Control;

public enum WorkerDynamicCircleModeValue { CylinderPlaneHoldPlaneNormal, CylinderPlaneHoldCylinderAxis, ConePlaneHoldPlaneNormal, ConePlaneHoldConeAxis, SpherePlaneIntersection, TwoConesIntersection, ConeCylinderIntersection }
