namespace Briosa.Worker.Control;

public enum WorkerRelationshipWeightingModeValue { NormalizeEquationCount, NormalizeEquationCountAndToleranceWidth, ResetAllWeights, NormalizeSquareRootEquationCount, NormalizeSquareRootAndToleranceWidth }
