using System.Collections.Frozen;

namespace Briosa.Worker.Control;

public static class WorkerInstrumentTypeNames
{
    // Exact SA 2024.1.0508.5 Add New Instrument choices; no name normalization.
    private static readonly FrozenSet<string> Supported = new[]
    {
        "AICON DPA",
        "AICON MoveInspect",
        "AICON ProCam 3D Probe",
        "API Ladar",
        "API Laser Rail",
        "API OmniTrac",
        "API OmniTrac2",
        "API Radian",
        "API Radian Plus/Core",
        "API Radian Pro",
        "API Tracker Device Interface",
        "API Tracker II",
        "API Tracker III",
        "Assembly Guidance Laser Projector",
        "Axxis 6-100 Arm (2.6m 6 dof)",
        "Axxis 6-200 Arm (3.2m 6 dof)",
        "Axxis 7-100 Arm Probe (2.6m 7 dof)",
        "Axxis 7-100 Arm Scanner (2.6m 7 dof)",
        "CimCore Arm 1024",
        "CimCore Arm 1028",
        "CimCore Arm 1030",
        "CimCore Arm 2200",
        "CimCore Arm 2500",
        "CimCore Arm 6DOF: 3012i, 5012, 1.2m",
        "CimCore Arm 6DOF: 3018i, 5018, 1.8m",
        "CimCore Arm 6DOF: 3024i, 5024, 2.4m",
        "CimCore Arm 6DOF: 3028i, 5028, 2.8m",
        "CimCore Arm 6DOF: 3036i, 5036, 3.6m",
        "CimCore Arm 6DOF: 5112, 1.2m",
        "CimCore Arm 6DOF: 5118, 1.8m",
        "CimCore Arm 6DOF: 5124, 2.4m",
        "CimCore Arm 6DOF: 5128, 2.8m",
        "CimCore Arm 6DOF: 5130, 3.0m",
        "CimCore Arm 6DOF: 5136, 3.6m",
        "CimCore Arm 7DOF: 5012Sc, 3012, 1.2m",
        "CimCore Arm 7DOF: 5018Sc, 3018, 1.8m",
        "CimCore Arm 7DOF: 5024Sc, 3024, 2.4m",
        "CimCore Arm 7DOF: 5028Sc, 3028, 2.8m",
        "CimCore Arm 7DOF: 5030Sc, 3030, 3.0m",
        "CimCore Arm 7DOF: 5036Sc, 3036, 3.6m",
        "CimCore Arm 7DOF: 5112Sc, 1.2m",
        "CimCore Arm 7DOF: 5118Sc, 1.8m",
        "CimCore Arm 7DOF: 5124Sc, 2.4m",
        "CimCore Arm 7DOF: 5128Sc, 2.8m",
        "CimCore Arm 7DOF: 5130Sc, 3.0m",
        "CimCore Arm 7DOF: 5136Sc, 3.6m",
        "Creaform VXelements",
        "Cubic KIT Theodolite",
        "Davis Perception II Weather Station",
        "Digital Network Level",
        "FARO Arm",
        "FARO Arm 1.5m 6 dof (QuantumS, QuantumM)",
        "FARO Arm 2.5m 6 dof (QuantumS, QuantumM)",
        "FARO Arm 2.5m 7 dof (QuantumS, QuantumM, Quantum Max)",
        "FARO Arm 2m 6 dof (QuantumS, QuantumM)",
        "FARO Arm 2m 7 dof (QuantumS, QuantumM, Quantum Max)",
        "FARO Arm 3.5m 6 dof (QuantumS, QuantumM)",
        "FARO Arm 3.5m 7 dof (QuantumS, QuantumM, Quantum Max)",
        "FARO Arm 3m 6 dof (QuantumS, QuantumM)",
        "FARO Arm 3m 7 dof (QuantumS, QuantumM, Quantum Max)",
        "FARO Arm 4m 6 dof (QuantumS, QuantumM)",
        "FARO Arm 4m 7 dof (QuantumS, QuantumM, Quantum Max)",
        "FARO Arm G04",
        "FARO Arm G04-05 (7dof)",
        "FARO Arm G08",
        "FARO Arm G08-05 (7dof)",
        "FARO Arm G12",
        "FARO Arm G12-05 (7dof)",
        "FARO Arm S08",
        "FARO Arm S12",
        "FARO Arm USB 10 ft. (Quantum, Fusion, Prime, Platinum)",
        "FARO Arm USB 10 ft. 7 dof (Quantum, Fusion, Prime, Platinum)",
        "FARO Arm USB 12 ft. (Quantum, Fusion, Prime, Platinum)",
        "FARO Arm USB 12 ft. 7 dof (Edge, Quantum, Fusion, Prime, Platinum)",
        "FARO Arm USB 4 ft. (Quantum, Prime, Platinum)",
        "FARO Arm USB 4 ft. 7 dof (Quantum, Prime, Platinum)",
        "FARO Arm USB 6 ft. (Quantum, Fusion, Prime, Platinum)",
        "FARO Arm USB 6 ft. 7 dof (Edge, Quantum, Fusion, Prime, Platinum)",
        "FARO Arm USB 8 ft.  (Quantum, Fusion, Prime, Platinum)",
        "FARO Arm USB 8 ft. 7 dof (Quantum, Fusion, Prime, Platinum)",
        "FARO Arm USB 9 ft. 7 dof (Edge)",
        "Faro Ion Tracker",
        "Faro Scanner Photon/LS/Focus 3D",
        "Faro Tracker",
        "Faro Vantage",
        "GSI V-STARS Photogrammetry System",
        "Generic Photogrammetry System",
        "Generic Photogrammetry System 2",
        "Hexagon Absolute 8 6dof-1.2m Compact",
        "Hexagon Absolute 8 6dof-2.5m",
        "Hexagon Absolute 8 6dof-2m",
        "Hexagon Absolute 8 6dof-3.5m",
        "Hexagon Absolute 8 6dof-3m",
        "Hexagon Absolute 8 6dof-4.5m",
        "Hexagon Absolute 8 6dof-4m",
        "Hexagon Absolute 8 7dof-2.5m",
        "Hexagon Absolute 8 7dof-2m",
        "Hexagon Absolute 8 7dof-3.5m",
        "Hexagon Absolute 8 7dof-3m",
        "Hexagon Absolute 8 7dof-4.5m",
        "Hexagon Absolute 8 7dof-4m",
        "Imported Measurements with Uncertainty",
        "Kern E2 Theodolite",
        "Kreon/API Ace-6-20",
        "Kreon/API Ace-6-25",
        "Kreon/API Ace-6-30",
        "Kreon/API Ace-6-35",
        "Kreon/API Ace-6-40",
        "Kreon/API Ace-6-45",
        "Kreon/API Ace-7-20",
        "Kreon/API Ace-7-25",
        "Kreon/API Ace-7-30",
        "Kreon/API Ace-7-35",
        "Kreon/API Ace-7-40",
        "Kreon/API Ace-7-45",
        "LAP CAD-Pro Laser Projector",
        "LPT Laser Projector",
        "Leica AT500",
        "Leica AT960/930",
        "Leica ATS600",
        "Leica Geosystems ScanStation PXX",
        "Leica Nova MS50 Total Station",
        "Leica Nova MS60 Total Station",
        "Leica T1200 Total Station",
        "Leica TDA5005 Total Station (GeoCOM)",
        "Leica TDRA6000 Total Station",
        "Leica TM6100A Theodolite",
        "Leica TPS Theodolite (1800)",
        "Leica TPS Theodolite (5100)",
        "Leica TPS Total Station (2003,5000,5005)",
        "Leica TS09 Total Station",
        "Leica TS15 Total Station",
        "Leica TS16 Total Station",
        "Leica TS30 Total Station",
        "Leica Total Station TC2000, TC2002",
        "Leica Tracker TP-LINK",
        "Leica emScon AT401",
        "Leica emScon AT402",
        "Leica emScon AT403",
        "Leica emScon Absolute Tracker (AT901 Series)",
        "Leica emScon Tracker (LT500-800 Series)",
        "Leica/Wild Theodolites T2000,T2002,T3000",
        "METRONOR Portable Measurement System",
        "Mitutoyo SpaceTrac-A",
        "Mitutoyo SpaceTrac-AI",
        "Mitutoyo SpaceTrac-AP",
        "Nikon Metrology APDIS MV400",
        "Nikon Metrology Laser Radar MV200",
        "Nikon Metrology Laser Radar MV300",
        "Nikon Metrology Surveyor v2",
        "Nivel 20 Two Axis Level",
        "On-Trak Laser Line System (OT-4040, OT-6000)",
        "PMT Arm 4m 7 dof",
        "Romer Absolute 7315",
        "Romer Absolute 7x20",
        "Romer Absolute 7x20SI/SE",
        "Romer Absolute 7x25",
        "Romer Absolute 7x25SI/SE",
        "Romer Absolute 7x30",
        "Romer Absolute 7x30SI/SE",
        "Romer Absolute 7x35",
        "Romer Absolute 7x35SI/SE",
        "Romer Absolute 7x40",
        "Romer Absolute 7x40SI/SE",
        "Romer Absolute 7x45",
        "Romer Absolute 7x45SI/SE",
        "Romer Multi-Gage",
        "SA Open Auxiliary Instrument",
        "SA Open Instrument",
        "SA Pipeline",
        "ScAlert Temperature Probe",
        "Sokkia Net-1 Total Station",
        "Sokkia Net-2 Total Station",
        "Sokkia Net05AX Total Station",
        "Sokkia Net05X Total Station",
        "Sokkia SETX Total Station",
        "Surphaser 10 Scanner",
        "Surphaser Scanner",
        "Thommen HM30 Weather Station",
        "Topcon MS AX Series Total Station",
        "Ultrasonic Thickness Gauge (CL400)",
        "Vicon Tracker",
        "Virtek Laser Projector",
        "XYZ Reference Frame",
        "Zeiss ETh 2 Theodolite",
    }.ToFrozenSet(StringComparer.Ordinal);

    public static bool IsSupported(string value) => Supported.Contains(value);
}
